services:
  app:
    build: .
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      DB_HOST: postgres
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - tutorial

  postgres:
    image: postgres:16-alpine
    container_name: ${DB_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT_DEFAULT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tutorial

  adminer:
    image: adminer
    container_name: ${AM_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "${AM_PORT}:${AM_PORT_DEFAULT}"
    networks:
      - tutorial
    depends_on:
      - postgres

networks:
  tutorial:
    driver: bridge

volumes:
  postgres_data:
    name: tutorial-laravel-postgres_data
